apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker
  labels:
    app: queue-worker
spec:
  selector:
    matchLabels:
      app: queue-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: queue-worker
    spec:
      containers:
      - name: queue-worker
        image: mrbolas/queue_worker:v0.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis-cart"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: ITEM_API_HOST
          value: "10.43.192.27"
        - name: ITEM_API_PORT
          value: "8080"